-- Add report workflow audit actions

ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'REPORT_REVIEW';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'REPORT_RESOLVE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'REPORT_DISMISS';
